# Generated by Django 4.2.13 on 2024-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpreter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='last_name',
        ),
    ]
