# Generated by Django 4.0.10 on 2024-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='ssn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
