# Generated by Django 4.0.10 on 2024-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0002_interpreter_address_interpreter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='ssn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
