# Generated by Django 4.2.13 on 2024-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0002_remove_interpreter_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='interpreter',
            name='languages',
            field=models.ManyToManyField(related_name='interpreters', to='interpreters.language'),
        ),
    ]
