# Generated by Django 4.2.13 on 2024-07-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0003_language_interpreter_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpreter',
            name='ssn',
        ),
    ]
