# Generated by Django 4.2.13 on 2024-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0007_remove_interpreter_address_interpreter_apt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreterapplicant',
            name='resume',
            field=models.FileField(default='Hi', upload_to='resume'),
            preserve_default=False,
        ),
    ]
