# Generated by Django 4.2.13 on 2024-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0008_interpreterapplicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
