# Generated by Django 4.2.13 on 2024-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0010_alter_interpreterapplicant_authorized_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='authorized_to_work',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='car_ownership',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='computer_ownership',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='currently_working',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='document_translation_service',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='home_office',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='interpretation_translation_training',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='interpreterapplicant',
            name='landline_phone_service',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
