# Generated by Django 4.2.13 on 2024-09-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0011_alter_interpreterapplicant_authorized_to_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='rate_of_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
