# Generated by Django 4.2.13 on 2024-09-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_country_alter_address_state'),
        ('interpreters', '0012_interpreter_rate_of_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpreter',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='interpreter',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]
