# Generated by Django 4.2.13 on 2024-07-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rate_of_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
