# Generated by Django 4.2.13 on 2024-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_rate_of_pay_alter_client_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
