# Generated by Django 4.2.13 on 2024-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone_number', models.CharField(max_length=15)),
                ('ceo_first_name', models.CharField(max_length=50)),
                ('ceo_last_name', models.CharField(max_length=50)),
                ('ceo_phone_phone', models.CharField(max_length=15)),
                ('ceo_email_address', models.EmailField(max_length=254)),
                ('poc_first_name', models.CharField(max_length=50)),
                ('poc_last_name', models.CharField(max_length=50)),
                ('poc_phone_phone', models.CharField(max_length=15)),
                ('poc_email_address', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=100)),
                ('apt_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('fax_number', models.CharField(blank=True, max_length=15, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('decline', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='apt_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Atlanta', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='GA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(default='Cathcart', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(default=30045, max_length=10),
            preserve_default=False,
        ),
    ]
