# Generated by Django 4.2.13 on 2024-08-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientapplicant_remove_client_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientapplicant',
            old_name='ceo_phone_phone',
            new_name='ceo_phone_number',
        ),
    ]
