# Generated by Django 4.2.13 on 2024-09-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_country_alter_address_state'),
        ('client', '0007_rename_poc_phone_phone_clientapplicant_poc_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]
