# Generated by Django 4.2.13 on 2024-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
