# Generated by Django 4.2.13 on 2024-09-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_notes_alter_assignment_parking_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='job',
            new_name='referring_job',
        ),
    ]
