# Generated by Django 4.2.13 on 2024-09-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_country_alter_address_state'),
        ('assignments', '0006_rename_referring_job_assignment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='location',
        ),
        migrations.AddField(
            model_name='assignment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]
