# Generated by Django 4.2.13 on 2024-09-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_assignment_location_assignment_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='address',
            new_name='location',
        ),
    ]
