# Generated by Django 4.2.13 on 2024-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_rename_address_assignment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
