# Generated by Django 4.2.13 on 2024-09-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_location_job_address'),
        ('assignments', '0009_alter_assignment_parking_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
