# Generated by Django 4.2.13 on 2024-07-19 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_job_id', models.CharField(max_length=100, null=True, unique=True)),
                ('job_date', models.DateField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(max_length=255)),
                ('practice_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('lep_name', models.CharField(max_length=50)),
                ('expected_duration', models.DurationField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
