# Generated by Django 4.2.13 on 2024-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expected_duration',
            field=models.TimeField(),
        ),
    ]
