# Generated by Django 4.2.13 on 2024-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_expected_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expected_duration',
            field=models.DurationField(),
        ),
    ]
